spring:
  datasource:
    url: jdbc:mysql://localhost:3333/activiti?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username : root
    password :
    driver-class-name: com.mysql.jdbc.Driver
